# Generated by Django 5.0.4 on 2024-04-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField(default='')),
                ('question_text', models.TextField(default='')),
                ('year', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('assertion', models.TextField(blank=True, default='', null=True)),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('list_i_heading', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_heading', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_i_option_a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_i_option_b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_i_option_c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_i_option_d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_option_1', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_option_2', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_option_3', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_option_4', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_ii_option_5', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('option_a', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('option_b', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('option_c', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('option_d', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('list_i_selection_text', models.TextField(blank=True, default='', null=True)),
                ('correct_answer_option', models.CharField(default='', max_length=1)),
                ('correct_answer_description', models.TextField(blank=True, default='', null=True)),
                ('question_type', models.CharField(default='', max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('negative_marks', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions_images')),
                ('table_head_a', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_b', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_c', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_d', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
