# Generated by Django 5.0.4 on 2024-04-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0002_question_level_of_defficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level_of_defficulty',
            field=models.ForeignKey(default='Medium', null=True, on_delete=django.db.models.deletion.CASCADE, to='question_module.defficultylevel'),
        ),
    ]
