# Generated by Django 5.0.4 on 2024-04-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0004_alter_question_level_of_defficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='negative_marks',
            field=models.DecimalField(decimal_places=2, default=1.33, max_digits=5),
        ),
    ]
