# Generated by Django 5.0.4 on 2024-04-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0005_alter_question_marks_alter_question_negative_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='multiple_choice', max_length=50),
        ),
    ]
