# Generated by Django 5.0.4 on 2024-05-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_module', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
